package main

// generated by glo

import (
    "context"
	"flag"
	"github.com/limoxi/ghost"
	"github.com/limoxi/ghost/cron"
	_ "&_{service_name}/api"
	_ "&_{service_name}/db"
	_ "&_{service_name}/cron"
	_ "&_{service_name}/middleware"
)

// initSystem 初始化系统
func initSystem() {
	ctx := context.WithValue(context.Background(), "db", ghost.GetDB())

	// todo
}

func main(){
    flag.Parse()
	args := flag.Args()
	if len(args) > 0 {
		switch args[0] {
		case "sync":
			ghost.SyncDB()
		case "init":
			initSystem()
		}
		return
	}

    cron.StartCronTasks()
	ghost.RunWebServer()
}