package api

// generated by glo
// import your api resources below

import (
	_ "&_{service_name}/api/dev"
	_ "&_{service_name}/api/op"
) // make sure this is the last line, or code gen will fail !!!